on:
  workflow_dispatch:
permissions:
  packages: write
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - uses: redhat-actions/podman-login@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - env:
        SIGSTORE_PRIVATE: ${{ secrets.SIGSTORE_PRIVATE }}
      run: |
        set -euxo pipefail
        ./setup.sh
        ./build.sh
